easy_admin:
    site_name: '%env(SITE_NAME)%'

    design:
        menu:
            - { route: 'homepage', label: 'Back to the website', icon: 'home' }
            - { route: 'security_logout', label: 'Log out', icon: 'sign-out' }

            - { label: 'Matchings' }
            - { route: 'admin_matches', label: 'Matches', icon: 'check' }
            - { route: 'admin_match_history', label: 'History', icon: 'history' }
            - { entity: 'Helper', label: 'Helpers', icon: 'users' }
            - { entity: 'HelpRequest', label: 'Help requests', icon: 'handshake-o' }
            - { entity: 'BlockedMatch', label: 'Blocked matches', icon: 'times' }

            - { label: 'Monitoring' }
            - { route: 'admin_statistics', label: 'Statistics', icon: 'chart-bar' }
            - { route: 'admin_unmatched_list', label: 'Unmatched needs', icon: 'search' }
            - { route: 'needs_map', label: 'Needs map', icon: 'map-o', target: '_blank' }

            - { label: 'Export' }
            - { route: 'admin_export_helpers', label: 'Export helpers', icon: 'cloud-download', target: '_blank' }
            - { route: 'admin_export_helpers_by_zip_code', label: 'Export zip codes', icon: 'cloud-download', target: '_blank' }
            - { route: 'admin_export_unmatched', label: 'Export unmatched', icon: 'cloud-download', target: '_blank' }

            - { label: 'Administration' }
            - { entity: 'Admin', label: 'Administrators', icon: 'users' }

    entities:
        Helper:
            class: App\Entity\Helper
            disabled_actions: ['show', 'new']
            list:
                title: Helpers
                max_results: 100
                sort: ['createdAt', 'DESC']
                actions:
                    - { name: 'edit', template: 'admin/actions/edit_helper.html.twig' }
                    - { name: 'delete', template: 'admin/actions/delete_helper.html.twig' }
                fields:
                    - id
                    - { property: 'zipCode', label: 'CP' }
                    - { property: 'firstName', label: 'First name' }
                    - { property: 'lastName', label: 'Last name' }
                    - { property: 'email', label: 'E-mail' }
                    - { property: 'canBabysit', label: 'Babysit' }
                    - { property: 'canBuyGroceries', label: 'Groceries' }
                    - { property: 'acceptVulnerable', label: 'Vulnerable' }
                    - { property: 'createdAt', label: 'Date' }

        HelpRequest:
            class: App\Entity\HelpRequest
            disabled_actions: ['show', 'new', 'edit']
            list:
                title: Help requests
                max_results: 100
                sort: ['createdAt', 'DESC']
                fields:
                    - id
                    - { property: 'zipCode', label: 'CP' }
                    - { property: 'helpType', label: 'Type' }
                    - { property: 'firstName', label: 'First name' }
                    - { property: 'lastName', label: 'Last name' }
                    - { property: 'email', label: 'E-mail' }
                    - { property: 'isMatched', type: 'boolean', label: 'Matched?' }
                    - { property: 'createdAt', label: 'Date' }

        BlockedMatch:
            class: App\Entity\BlockedMatch
            disabled_actions: ['show', 'new', 'edit']
            list:
                title: Blocked matches
                max_results: 100
                sort: ['createdAt', 'DESC']
                fields:
                    - id
                    - { property: 'owner', label: 'Requester' }
                    - { property: 'helper.firstName', label: 'Helper first name' }
                    - { property: 'helper.lastName', label: 'Helper last name' }
                    - { property: 'createdAt', label: 'Date' }

        Admin:
            class: App\Entity\Admin
            controller: App\Controller\Admin\AdminController
            list:
                title: Site administrators
                max_results: 10
                sort: ['username', 'ASC']
                fields:
                    - { property: 'username', label: 'Administrator' }
            form:
                title: 'Add administrator'
                help: "We're not going to check, but please ensure you use a suitably secure password!"
                fields:
                    - { property: 'username', type: 'text', label: 'Username' }
                    - { property: 'plain_password', type: 'repeated', type_options: { type: Symfony\Component\Form\Extension\Core\Type\PasswordType, invalid_message: 'Both passwords must match', first_options: { label: 'Password' }, second_options: { label: 'Confirm password' }, required: true } }
            edit:
                title: 'Edit administrator'
